### ISSUE TITLE
When Moodle Drupal Integration i have faced this issue i couldnt figure out

### ISSUE THREAD

**Issue by shanky1712** [cannod/moodle-drupalservices#35]
The following messages are the results of tests of the configuration below. Use these to guide you through the setup and configuration of the Drupal Services plugin. If you see any items with 'fail', you'll need to resolve them in order for this plugin to work.
Fail : cookies: SSO Cookie not discovered. 1) check that you are currently logged in to drupal. 2) Check that Drupal's session cookie is configured in settings.php 3) check that cookie_domain is properly filled in.
Fail : system/connect: User session data reachable but you aren't logged in!
Success : user/login: Logged in to drupal!
Success : muser/Index: User listings are active!

**Comment by jaswant-tak** [comment]
Hi I have configured as per the instructions. my Drupal is on root domain while Moodle is on subdomain. Now when I go to Moodle for auth plugin settings I can see only "Drupal Website URL" field nothing else. When I put the Drupal URL into it I am getting debug messages like "The moodlesso service is unreachable. Please verify that you have the Mooodle SSO drupal module installed and enabled: http://drupal.org/project/moodle_sso "

I have checked on Drupal side everything is properly installed and plugin is enabled as per the instruction. Also when I try to access http://www.<mydrupal.com>/moodlesso/moodlesso I am getting blank white screen. Nothing is displayed here. Can you please help me to fix it.

Many thanks

**Comment by netw3rker** [comment]
Hi @jaswant-tak,

I'm happy to help, but two things first. 1) it would be great if you could start a new issue instead of commenting on a closed issue that isn't really related to your problem. 2) if you feel that you are experience the same problem as a closed issue, you should also then re-open it. I ask this because I don't typically monitor the closed issues for additional support requests.

You shouldn't try to access the services that the moodle_sso module supplies directly. Most of them require them to be composed as an HTTP POST request, so viewing them from a browser is difficult.

It sounds like one of a couple of problems has happend. 1) make absolutely sure that you have set your Drupal site to share its session cookie. this means editing your drupal settings.php file located in sites/default/settings.php (or possibly sites/[your domain]/settings.php). the $cookie_domain variable should be both uncommented (no leading # sign) and changed to be the name of your domain, with a dot at the beginning (for example ".example.com" ).

when you configure the auth_drupalservices plugin in moodle, you need to give it just the domain of your Drupal site. in your case,  the Drupal url is just "http://example.com".

Hope this helps. Please open a new issue/support request if you continue having problems.
Thanks!
